apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: egress-watcher-service-account
  namespace: egress-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: egress-watcher-role
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - serviceentries
  verbs:
  - watch
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: egress-watcher-role-binding
subjects:
  - kind: ServiceAccount
    name: egress-watcher-service-account
    namespace: egress-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: egress-watcher-role